const DataPlanos = {
  A: {
    areas: {
      plantaBaja: 87.88,
      plantaAlta: 11.24,
      total: 198.9,
    },
    detalle: {
      dormitorios: 4,
      balcones: 0,
      baños: 4,
      patio: 40.81,
      extras: [
        "Dormitorio master con vestidor",
        "Comedor",
        "Sala de Estar",
        "Cocina con Despensa",
        "Baño Social",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
  B1: {
    areas: {
      plantaBaja: 88.05,
      plantaAlta: 89.7,
      total: 177.75,
    },
    detalle: {
      dormitorios: 4,
      balcones: 2,
      baños: 3,
      patio: 40.32,
      extras: [
        "Dormitorio master con vestidor",
        "Comedor",
        "Recibidor",
        "Sala de Estar",
        "Cocina con Despensa",
        "Baño Social",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
  B2: {
    areas: {
      plantaBaja: 88.05,
      plantaAlta: 89.7,
      total: 177.75,
    },
    detalle: {
      dormitorios: 3,
      balcones: 2,
      baños: 3,
      patio: 40.32,
      extras: [
        "Dormitorio master con vestidor",
        "Sala Familiar",
        "Comedor",
        "Recibidor",
        "Sala de Estar",
        "Cocina con Despensa",
        "Baño Social",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
  C: {
    areas: {
      plantaBaja: 75.58,
      plantaAlta: 79.81,
      total: 155.17,
    },
    detalle: {
      dormitorios: 3,
      balcones: 1,
      baños: 2,
      patio: 61.8,
      extras: [
        "Dormitorio master con vestidor",
        "Comedor",
        "Sala de Estar",
        "Cocina America",
        "Baño Social",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
  D: {
    areas: {
      plantaBaja: 79.22,
      plantaAlta: 84.38,
      total: 163.6,
    },
    detalle: {
      dormitorios: 3,
      balcones: 0,
      baños: 3,
      patio: 59.18,
      extras: [
        "Dormitorio master con vestidor",
        "Comedor",
        "Sala",
        "Cocina con Despensa",
        "Baño Social",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
  D2: {
    areas: {
      plantaBaja: 79.22,
      plantaAlta: 84.38,
      total: 163.6,
    },
    detalle: {
      dormitorios: 3,
      balcones: 0,
      baños: 3,
      patio: 59.18,
      extras: [
        "Dormitorio master con vestidor",
        "Comedor",
        "Recibidor",
        "Sala",
        "Cocina con Despensa",
        "Baño Social",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
  E: {
    areas: {
      plantaBaja: 92.58,
      plantaAlta: 108.88,
      total: 201.44,
    },
    detalle: {
      dormitorios: 4,
      balcones: 0,
      baños: 4,
      patio: 42.08,
      extras: [
        "Dormitorio master con vestidor",
        "Sala Comedor",
        "Recibidor",
        "Sala Familiar",
        "Cocina con Despensa",
        "Baño Social",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
  E2: {
    areas: {
      plantaBaja: 93.12,
      plantaAlta: 108.74,
      total: 201.86,
    },
    detalle: {
      dormitorios: 3,
      balcones: 0,
      baños: 3,
      patio: 51.66,
      extras: [
        "Dormitorio master con vestidor",
        "Sala Comedor",
        "Recibidor",
        "Sala Familiar",
        "Cocina con Despensa",
        "Baño Social",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
  E3: {
    areas: {
      plantaBaja: 93.12,
      plantaAlta: 108.74,
      total: 201.86,
    },
    detalle: {
      dormitorios: 2,
      balcones: 0,
      baños: 3,
      patio: 51.66,
      extras: [
        "Dormitorio master con vestidor",
        "Sala Comedor",
        "Recibidor",
        "Sala Familiar",
        "Cocina con Despensa",
        "Baño Social",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
  F1: {
    areas: {
      plantaBaja: 92.58,
      plantaAlta: 106.72,
      total: 199.3,
    },
    detalle: {
      dormitorios: 3,
      balcones: 0,
      baños: 3,
      patio: 42.08,
      extras: [
        "Dormitorio master con vestidor",
        "Sala Comedor",
        "Recibidor",
        "Sala Bar",
        "Sala Familiar",
        "Cocina con Despensa",
        "Baño Social",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
  F2: {
    areas: {
      plantaBaja: 92.58,
      plantaAlta: 106.72,
      total: 199.3,
    },
    detalle: {
      dormitorios: 3,
      balcones: 0,
      baños: 3,
      patio: 42.08,
      extras: [
        "Dormitorio master con vestidor",
        "Sala Comedor",
        "Recibidor",
        "Sala Bar",
        "Sala Familiar",
        "Cocina con Despensa",
        "Baño Social",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
  G1A: {
    areas: {
      plantaBaja: 92.54,
      plantaAlta: 86.87,
      total: 179.41,
    },
    detalle: {
      dormitorios: 2,
      balcones: 0,
      baños: 1,
      patio: 1,
      extras: [
        "Dormitorio master con vestidor",
        "Sala de Estar",
        "Recibidor",
        "Sala",
        "Comedor",
        "Cocina",
        "Estudio",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
  G1B: {
    areas: {
      plantaBaja: 92.54,
      plantaAlta: 86.87,
      total: 179.41,
    },
    detalle: {
      dormitorios: 3,
      balcones: 0,
      baños: 1,
      patio: 1,
      extras: [
        "Dormitorio master con vestidor",
        "Sala de Estar",
        "Recibidor",
        "Sala",
        "Comedor",
        "Cocina",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
  G2A: {
    areas: {
      plantaBaja: 92.54,
      plantaAlta: 86.87,
      total: 179.41,
    },
    detalle: {
      dormitorios: 2,
      balcones: 0,
      baños: 1,
      patio: 1,
      extras: [
        "Dormitorio master con vestidor",
        "Sala de Estar",
        "Recibidor",
        "Sala",
        "Estudio",
        "Comedor",
        "Cocina",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
  G2B: {
    areas: {
      plantaBaja: 92.54,
      plantaAlta: 86.87,
      total: 179.41,
    },
    detalle: {
      dormitorios: 3,
      balcones: 0,
      baños: 1,
      patio: 1,
      extras: [
        "Dormitorio master con vestidor",
        "Sala de Estar",
        "Recibidor",
        "Sala",
        "Comedor",
        "Cocina",
        "Dormitorio de servicio con baño",
        "Lavanderia",
      ],
    },
  },
};

export default DataPlanos;
